services:
  web:
    build: .
    ports:
      - "8080:80"  # Map host port 8080 to container port 80
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "todo"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
