version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
      MYSQL_DATABASE: todo
      MYSQL_USER: devops_user
      MYSQL_PASSWORD: devops_password
    command: [
      "--explicit_defaults_for_timestamp=1",
      "--tls_version=TLSv1.2,TLSv1.3",
      "--pid-file=/var/lib/mysql/mysqld.pid"
    ]
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    environment:
      DB_HOST: db
      DB_USER: devops_user
      DB_PASSWORD: devops_password
      DB_NAME: devops_db
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: my-secret-password
    depends_on:
      - db

volumes:
  db_data:
